### ISSUE TITLE
#VALVE_REJECT_LAN_GAME

### ISSUE THREAD

**Issue by nightwatchmaker** [kyleraykbs/Portal2-32PlayerMod#135]
I used the sv_lan 1 to fix no steam logon, but i saw a friend get kicked for #VALVE_REJECT_LAN_GAME after like 10 minutes.

**Comment by OrsellGit** [comment]
This sometimes happens rarely. A solution, if you aren't already doing this, is to use playit.gg, which will forward your clients, your friend, to you the host.

**Comment by OrsellGit** [comment]
@nightwatchmaker has the issue been resolved?

**Comment by nightwatchmaker** [comment]
> This sometimes happens rarely. A solution, if you aren't already doing this, is to use playit.gg, which will forward your clients, your friend, to you the host.

i'm gonna try that

**Comment by scipply** [comment]
@nightwatchmaker now iti probably works even without playit. just port forward and done

**Comment by Back-Slash-N** [comment]
@nightwatchmaker the No Steam Logon error has now been fixed by valve, meaning you do not need sv_lan 1 at all now.

**Comment by nightwatchmaker** [comment]
oh ok

**Comment by nightwatchmaker** [comment]
> @nightwatchmaker now iti probably works even without playit. just port forward and done

Oh ok, my friends didn't use it anyway

**Comment by nightwatchmaker** [comment]
> @nightwatchmaker now iti probably works even without playit. just port forward and done

Oh ok, my friends didn't use it anyway
