### ISSUE TITLE
Make All Coop Player Droppers Stay Open

### ISSUE THREAD

**Issue by OrsellGit** [kyleraykbs/Portal2-32PlayerMod#137]
Make the Coop spawn droppers stay open instead of automatically closing. They keep causing problems with players getting stuck. This is an easy add, but this issue is acting as a reminder as I'm currently working on other things.

**Comment by scipply** [comment]
maybe you should try using a todo app like the one from microsoft. not saying that you should move from using issues to using the app, but ig that could help you with managing stuff overall

**Comment by OrsellGit** [comment]
Technically, this is an issue, so this is the right place to post them. But if I don't, I will forget. I do write down things I need to do, but I write down more important things than this.

**Comment by OrsellGit** [comment]
Solved issue in commit: https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/commit/4533f7a175f9b2ba7a8264f0914cdfc1b7d2903a
