### ISSUE TITLE
Launcher doesn't update

### ISSUE THREAD

**Issue by nightwatchmaker** [kyleraykbs/Portal2-32PlayerMod#138]
When I get in the launcher it asks me to update and I click yes… launcher closes and nothing happens

**Comment by Back-Slash-N** [comment]
Could you send your logs? Should be in Documents/p2mm/Logs

**Comment by OrsellGit** [comment]
@nightwatchmaker can you send your logs?

**Comment by OrsellGit** [comment]
Closing as the issue has gone stale.

**Comment by nightwatchmaker** [comment]
wait unclose it im still here after a while, also how do i send logs

**Comment by OrsellGit** [comment]
@nightwatchmaker Get the logs from the local p2mm folder. Located in `Documents` on windows and Steam Decl, `.config` for linux.

**Comment by OrsellGit** [comment]
@nightwatchmaker im closing this again. Make a new issue post if you are gonna post your logs.
