### ISSUE TITLE
Current state of single-player campaign co-op?

### ISSUE THREAD

**Issue by Void48** [kyleraykbs/Portal2-32PlayerMod#139]
Hey, I've been planning to play through the single-player campaign with my friend and I was wondering if all the issues have been fixed. I remember the last time we tried to play, we ran into some issues that either prevented us from progressing or made it very difficult to continue. (I can't currently remember which specific issue it was.)

**Comment by OrsellGit** [comment]
I don't remember what your Discord username was, so I can't look you up for what issues you had. However, on `dev`, a bunch of things have been fixed, not sure about `main` however. If you want you can try out the `dev` branch.

**Comment by Void48** [comment]
> I don't remember what your Discord username was, so I can't look you up for what issues you had. However, on `dev`, a bunch of things have been fixed, not sure about `main` however. If you want you can try out the `dev` branch.

We're ok with waiting until the `dev` branch merges into `main`, but thanks for the heads up!

**Comment by OrsellGit** [comment]
Ok glad to hear I'll be closing this now.
