### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by backslashin** [kyleraykbs/Portal2-32PlayerMod#25]
in course 5 the doors are already open without 2 people meaning anyone can changelevel
![image](https://user-images.githubusercontent.com/83998661/168094071-5b6343d8-e13f-4f9c-8afe-e9f5663f881c.png)

**Comment by KonradCzerw** [comment]
as far as i remember this is intended behaviour since the doors were buggy with many players arround

**Comment by backslashin** [comment]
Oh ok

**Comment by kyleraykbs** [comment]
I'll probably rework this when we make the new HUB
