### ISSUE TITLE
Languages Crash Bug

### ISSUE THREAD

**Issue by OrsellGaming** [kyleraykbs/Portal2-32PlayerMod#40]
When adding a new custom language to the launcher or adding new options to the current languages, the launcher will crash instantly if any translations aren't defined or are missing from the language JSON files. There should be a catch in case a translation isn't defined correctly to prevent it from crashing.

This bug isn't a priority to fix. Just mainly an issue that can occur when adding new menu options or for those wanting to add new translations and forgetting an option causing a crash. This will also be an issue if they have no idea exactly how MainWindow.py works.

Here's an example from when I was trying to add something:
![image](https://user-images.githubusercontent.com/34631691/190546610-79233973-fa78-43c6-b167-add5a8aa08a8.png)

@cabiste69

**Comment by cabiste69** [comment]
this can be fixed by checking if the keys of the language file are the same as the template (english.json in our case) so uh... sure i'll fix it when i have time
