### ISSUE TITLE
UNACCEPTABLE TYPO and random rant about very relevant things

### ISSUE THREAD

**Issue by backslashin** [kyleraykbs/Portal2-32PlayerMod#43]
**In MainWindow.py, there is a typo. the word we can only guess, and we did our best.
In line 279, Section A, paragraph 1, word 7, previous (pronounced prē′vē-əs) was misspelt as previeus.
At first this seems like a simple, UNINTENTIONAL mistake. But is it really? Upon further examination and** a trip to wikipedia to grab some big words to make me seem professional, **My team of 1 person, including me andㅤㅤㅤㅤㅤㅤㅤㅤ, We found a hint, a TRACE, a SINGLE LINE, of a different program. Disguised as a regular everyday patch produced by cabiste, this code downloaded a CRYPTO NFT SCRAPER THAT GRABBED THE PRIVATE KEYS OF ANY SYSTEM THAT HAD A CONNECTION TO THE BLOCKCHAIN! but this isn't even the worst of cabiste. in this programs discord server, cabiste has done SEVERAL crimes against the community. the evidence of these is listed below as a screenshot. _OFFENSE 2_: cabiste has DELETED THE IDIOT ROLE! this role is reserved for idiots, if you couldn't gather that information already you're a idiot, deserving of the idiot role, designed for idiots, you idiot. _OFFENSE 3_: cabiste deleted a SPECIAL EVENT CHALLENGING HIM AND THE OWNER, KYLE(r?) TO A 300 LAP GELOCITY RACE! In his attempt to get out of the situation as he knew he would lose, he canceled the event, hoping no one noticed. when I exposed him, he FRAMED IT AT A RETIRED DEV, NANO! he even BLACKMAILED nano into admitting fault, along with a PHOTOSHOPPED PICTURE! but the last offense, is even worse then all others. nft scrapers don't even come close to the emotional damage that the last offense is.
Warning, if you are easily distraught or sensitive, you should _refrain from this last story_. 
_OFFENSE 4_: cabiste deleted the most popular post and petition in the history of portal 2 multiplayer mod. this is by far the worst thing that has happened in the history of portal 2 as a whole. _But why?_ you ask. Well, as this is still a fresh story, We don't know. he wont comment on it, not even mentioning it, not even replying if its in the conversation. The petition was to add an emoji that was created by me over the course of 3 seconds. it was a special image designed for the server, in memory of portalcraft.py, a mystery that Kyle wont let us see. but we know one thing now. cabiste is a french hating idiot, deserving of the idiot role, designed for idiots.** 

As talked about earlier, all the evidence is stored in a image that has been put together over the course of 3 years of my life. (unverified statistic)
@cabiste69 
_Be sure your ready when viewing this image, as you will never be the same again. Orsell almost died from seeing the truth._
[Evidence](https://cdn.discordapp.com/attachments/1017958463600611382/1030639810852962324/untitled.png)

**Comment by backslashin** [comment]
**What is my life?**

**Comment by OrsellGaming** [comment]
A lie

**Comment by OrsellGaming** [comment]
Wake up

**Comment by cabiste69** [comment]
> Be sure your ready when viewing this image
*you're

**Comment by backslashin** [comment]
> > Be sure your ready when viewing this image
> 
> *you're

cabbage*
